### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by DanielLvovsky** [CoolProgrammerAK/LinkZone#1]
Hi there,

So I am getting an issue when trying to run this app locally. I have ran the command npm install and once I run npm start it gives me this error.

![Screenshot 2020-11-02 125422](https://user-images.githubusercontent.com/54752143/97918186-8dc04a80-1d0a-11eb-8b13-48af8f72470b.png)

Is there a solution for this?

Thanks,
Daniel

**Comment by DanielLvovsky** [comment]
nvm I fixed this error.

I also have one more question, do you have to be signed-in in order to access the bio link?

**Comment by CoolProgrammerAK** [comment]
yess

**Comment by CoolProgrammerAK** [comment]
Hope this problem get solved
